views:
  - name: post_submission_deployments_view
    cubes:
      - join_path: post_submission_deployments
        includes:
          - deployment_date
          - deployment_month
          - deployment_hour
          - is_verified
          - count 